import tkinter
class ThumbHistApp():
    def __init__(self):
        wd = tkinter.Tk()
        wd.title(u'Landsat数据挑选')
        startdateT = tkinter.Entry(wd, width=20)
        startdateT.grid(column=1, row=0)
        lbsd = tkinter.Label(wd, text="Start Date: ")
        lbsd.grid(column=0, row=0)
        enddateT = tkinter.Entry(wd, width=20)
        enddateT.grid(column=1, row=1)
        lbed = tkinter.Label(wd, text="End Date: ")
        lbed.grid(column=0, row=1)
        workdirT = tkinter.Entry(wd, width=20)
        workdirT.grid(column=1, row=2)
        lbwd = tkinter.Label(wd, text="Work Directory: ")
        lbwd.grid(column=0, row=2)
        prdefT = tkinter.Entry(wd, width=20)
        prdefT.grid(column=1, row=3)
        lbprd = tkinter.Label(wd, text="Path/Row Definition: ")
        lbprd.grid(column=0, row=3)
        refT = tkinter.Entry(wd, width=20)
        refT.grid(column=1, row=4)
        lbref = tkinter.Label(wd, text="Reference Dir: ")
        lbref.grid(column=0, row=4)
        indexT = tkinter.Entry(wd, width=20)
        indexT.grid(column=1, row=5)
        lbindex = tkinter.Label(wd, text="Index File: ")
        lbindex.grid(column=0, row=5)
        multiT = tkinter.Entry(wd, width=20)
        multiT.grid(column=1, row=6)
        lbmlt = tkinter.Label(wd, text="Num of Threads: ")
        lbmlt.grid(column=0, row=6)

        wd.mainloop()

if __name__ == '__main__':
    app = ThumbHistApp()